# Generated by Django 4.1.3 on 2022-11-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='모델명')),
                ('description', models.CharField(blank=True, help_text='설명을 적어주세요.', max_length=100, verbose_name='설명')),
                ('upload', models.FileField(blank=True, max_length=254, upload_to='')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'ordering': ('update_dt',),
            },
        ),
    ]
