# Generated by Django 3.2 on 2022-11-23 02:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_aimodel_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('hit', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='upload',
            new_name='file',
        ),
        migrations.AddField(
            model_name='post',
            name='used',
            field=models.BooleanField(default=False, unique=True, verbose_name='운영중'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
